import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import SessionWrapper from "@/components/SessionWrapper"; // Adjust the import path as necessary

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" >
      <body>
        <SessionWrapper>{children}</SessionWrapper> {/* Wrap children with SessionProvider using the new component */}
      </body>
    </html>
  );
}
